- frontend/src/components/kvalitetsregistrering/kvalitetsskjema/annet.tsx
> Conditional show Annet

- frontend/src/components/kvalitetsregistrering/error-messages.tsx
- frontend/src/components/kvalitetsregistrering/footer.tsx
- frontend/src/redux-api/saksdata.ts
> Add status and action sticky footer

- frontend/src/components/kvalitetsregistrering/saksdata/tilknyttet-enhet.tsx
> Fix name box width

- frontend/src/components/kvalitetsregistrering/error-messages.tsx
- frontend/src/components/kvalitetsregistrering/footer.tsx
- frontend/src/hooks/use-validation-error.ts
- frontend/src/redux-api/saksdata.ts
> Fullfoer cache key

- frontend/src/components/kvalitetsregistrering/saksdata/tilknyttet-enhet.tsx
- frontend/src/types/user.ts
> Only let user choose between klageenheter they have access to

- frontend/src/components/kvalitetsregistreringer/kvalitetsregistreringer.tsx
> Fix wrong enhetId on creating saksdata

- frontend/src/components/kvalitetsregistrering/saksdata/fra-vedtaksenhet.tsx
- frontend/src/components/kvalitetsregistrering/saksdata/styled-components.ts
- frontend/src/components/kvalitetsregistrering/saksdata/ytelse.tsx
- frontend/src/hooks/use-kodeverk-value.ts
> Show ytelse for finished vurdering

- frontend/src/components/date-picker-with-error/date-picker-with-error.tsx
- frontend/src/components/kvalitetsregistrering/saksdata/mottatt-klageinstans.tsx
- frontend/src/components/kvalitetsregistrering/saksdata/mottatt-vedtaksinstans.tsx
> Validate input in date-picker

- frontend/src/components/oversikt/charts/hjemler.tsx
> Fix graph tooltip

- frontend/src/components/oversikt/styled-components.ts
> Fix layout

- frontend/src/components/oversikt/hooks/use-statistics.ts
> Fix loading overlay

- frontend/src/components/oversikt/charts/kvalitetsvurdering.tsx
> Use mangelfullt total as total in graph %

- frontend/src/components/oversikt/oversikt.tsx
> Move behandlingstid up

- frontend/src/components/oversikt/card/card.tsx
- frontend/src/components/oversikt/charts/behandlingstid-over-time.tsx
- frontend/src/components/oversikt/charts/kvalitetsvurdering.tsx
- frontend/src/components/oversikt/charts/registrering-time-distribution.tsx
- frontend/src/components/oversikt/hooks/use-buckets.ts
- frontend/src/components/oversikt/oversikt.tsx
- frontend/src/components/oversikt/pills/pills.tsx
- frontend/src/components/oversikt/styled-components.ts
> Statistics: Add dynamic layout, color behandlingstid buckets

- frontend/src/components/kvalitetsregistrering/kvalitetsskjema/kvalitetsskjema.tsx
> Hide kvalitetsskjema on utfall Trukket

- frontend/src/components/oversikt/charts/mangelfullt-over-time.tsx
- frontend/src/types/statistics.ts
> Sort y axis on mangelfullt over time

- frontend/src/components/oversikt/charts/kvalitetsvurdering.tsx
> Show percentage in doughnut

- frontend/src/components/routing/nav.tsx
- frontend/src/components/routing/routes.tsx
- frontend/src/components/statistikk/charts/kvalitetsvurdering.tsx
- frontend/src/components/statistikk/hooks/use-behandlingstid-param.ts
- frontend/src/components/statistikk/leder/hooks/use-statistics.ts
- frontend/src/components/statistikk/min/filters.tsx
- frontend/src/components/statistikk/min/hooks/use-statistics.ts
- frontend/src/components/statistikk/min/min-statistikk.tsx
- frontend/src/components/statistikk/total/hooks/use-statistics.ts
- frontend/src/pages/statistikk/min.tsx
- frontend/src/redux-api/statistics.ts
- frontend/src/types/statistics.ts
> Add min statistikk

- frontend/src/components/statistikk/open/openstatistikk.tsx
> Add disclaimer for open stats

- frontend/src/components/filters/date-presets/constants.ts
- frontend/src/components/filters/date.tsx
- frontend/src/components/filters/hooks/use-query-filter.ts
- frontend/src/components/statistikk/leder/filters.tsx
- frontend/src/components/statistikk/leder/hooks/use-statistics.ts
- frontend/src/components/statistikk/min/filters.tsx
- frontend/src/components/statistikk/min/hooks/use-statistics.ts
- frontend/src/components/statistikk/open/filters.tsx
- frontend/src/components/statistikk/open/hooks/use-statistics.ts
- frontend/src/components/statistikk/total/filters.tsx
- frontend/src/components/statistikk/total/hooks/use-statistics.ts
- frontend/src/components/tilbakemeldinger/filters.tsx
- frontend/src/components/tilbakemeldinger/hooks/use-filtered-saksdata.ts
- frontend/src/components/tilbakemeldinger/hooks/use-filtered-statistics.ts
- frontend/src/hooks/use-default-query-params.ts
> Change from last 30 days to this month everywhere

- frontend/src/components/date-picker-with-error/date-picker-with-error.tsx
- frontend/src/components/kvalitetsvurdering/kvalitetsskjema/klageforberedelsen.tsx
- frontend/src/components/kvalitetsvurdering/kvalitetsskjema/styled-components.ts
- frontend/src/components/kvalitetsvurdering/saksdata/mottatt-vedtaksinstans.tsx
> Add missing help texts

- frontend/src/components/kvalitetsvurdering/saksdata/lovhjemmel/lovhjemmel.tsx
> Add missing help text for hjemmel

- server/src/auth/session-utils.ts
> Revert "Remove secure cookie attribute in dev"

- frontend/src/components/statistikk/charts/utfall-graph.tsx
- frontend/src/types/utfall.ts
> Add innstilling utfall

- frontend/src/components/date-picker/date-picker.tsx
- frontend/src/components/filters/date-presets/constants.ts
- frontend/src/components/filters/month.tsx
- frontend/src/components/kvalitetsvurdering/saksdata/mottatt-klageinstans.tsx
- frontend/src/components/kvalitetsvurdering/saksdata/mottatt-vedtaksinstans.tsx
- frontend/src/components/statistikk/charts/kvalitetsvurderinger/mangelfullt-over-time.tsx
- frontend/src/components/statistikk/hooks/use-buckets.ts
- frontend/src/domain/date.ts
- frontend/src/functions/format-id.ts
- frontend/tsconfig.json
> Auto-fix short dates from user + fix noUncheckedIndexedAccess errors

- frontend/src/components/date-picker/date-picker.tsx
> Add auto-expand for very short dates

- frontend/src/components/statistikk/key-stats/finished.tsx
> "Fullførte vuderinger" -> "Registrerte saker"

- frontend/src/components/statistikk/comparison/hooks/use-statistics-v2.ts
> Sammenlikning: implement missing filters

- frontend/src/colors/colors.ts
- frontend/src/simple-api-state/use-utfall.ts
- frontend/src/types/utfall.ts
> Remove Trygderetten-utfall from statistics filter
